# Generated by Django 4.0.2 on 2022-02-23 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('discount_percentage', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default/default_profile_image.png', upload_to='profile_pics')),
                ('org_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Name')),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, choices=[('harare', 'Harare'), ('bulawayo', 'Bulawayo'), ('midlands', 'Midlands'), ('manicaland', 'Manicaland'), ('masvingo', 'Masvingo'), ('mash_east', 'Mashonaland East'), ('mash_west', 'Mashonaland West'), ('mash_central', 'Mashonaland Central'), ('mat_north', 'Matabeleland North'), ('mat_south', 'Matabeleland South')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Mobile Number - (e.g. 0776887606', max_length=10)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('ecocash', 'Ecocash'), ('onemoney', 'OneMoney')], max_length=10)),
                ('expire_date', models.DateField()),
                ('reference_code', models.TextField()),
                ('poll_url', models.TextField(null=True)),
                ('payment_status', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Information',
            },
        ),
    ]
