# Generated by Django 4.0.2 on 2022-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name_plural': 'Bill Payments'},
        ),
        migrations.AddField(
            model_name='billing',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
