# Generated by Django 4.0.2 on 2022-03-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_billing_options_billing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='in the format: 07xxx', max_length=10, null=True),
        ),
    ]
