# Generated by Django 4.0.2 on 2022-03-26 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 4, 26)),
        ),
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='2x8p7m0m13ammewckw1e'),
        ),
    ]
