# Generated by Django 4.0.2 on 2022-04-11 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_billing_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 5, 11)),
        ),
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='d0sh1w8eqvtbqiwy13cu'),
        ),
    ]
