# Generated by Django 4.0.2 on 2022-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_billing_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='d7x3ox0ay7hcaiqx1bi9'),
        ),
    ]
