# Generated by Django 4.0.2 on 2022-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_billing_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='vh9tmose2nk957k0wopd'),
        ),
    ]
