# Generated by Django 4.0.2 on 2022-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_billing_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='4o6s0g8naogdl0tise6g'),
        ),
    ]
