# Generated by Django 4.0.6 on 2022-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_billing_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.CharField(choices=[('800', 'Starter ($1.00)'), ('4000', 'Premium ($5.00)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='bt1lk693pftjw55drpst'),
        ),
    ]
