# Generated by Django 4.0.6 on 2022-09-21 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_billing_amount_alter_billing_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.CharField(choices=[('800', 'Starter ($1.00)'), ('4000', 'Premium ($5.00)')], help_text='For pricing refer to the pricing models <a href="#">here</a>', max_length=50, verbose_name='Subscription Plan'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 21)),
        ),
        migrations.AlterField(
            model_name='billing',
            name='reference_code',
            field=models.TextField(default='g7loq7u86x7lxjqih5yg'),
        ),
    ]
