# Generated by Django 4.0.6 on 2022-07-14 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(default='placeholder_item_image.png', upload_to='advert_cover_images')),
                ('item_type', models.CharField(choices=[('good', 'Goods'), ('service', 'Services')], max_length=10)),
                ('description', models.TextField(help_text='Describe the goods/service offered in detail')),
                ('price', models.FloatField(help_text='How much do these cost?')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='advert_image_one')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='advert_image_two')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='advert_image_three')),
                ('advert_reference', models.TextField(default='rj23rzwoohegk21xhazb')),
                ('slug', models.SlugField(editable=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Client Adverts',
            },
        ),
    ]
