# Generated by Django 4.0.6 on 2022-07-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_advert_item_category_alter_advert_advert_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='1vgp81fb6u8bxghkweh1'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.FloatField(),
        ),
    ]
