# Generated by Django 4.0.6 on 2022-07-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_advert_advert_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='location_province',
            field=models.CharField(choices=[('harare', 'Harare'), ('bulawayo', 'Bulawayo'), ('manicaland', 'Manicaland'), ('midlands', 'Midlands'), ('masvingo', 'Masvingo'), ('mash_east', 'Mash-East'), ('mash_central', 'Mash Central'), ('mash_west', 'Mash West'), ('mat_south', 'Mat South'), ('mat_north', 'Mat-North')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='yuznwy0zm93y6oekaggh'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='item_category',
            field=models.CharField(choices=[('property', 'Property'), ('home_appliances', 'Home Appliances'), ('electronics', 'Electronics'), ('health_and_beauty', 'Health & Beauty'), ('automotive', 'Automotive'), ('furniture', 'Furniture'), ('real_estate', 'Real Estate'), ('jobs', 'Jobs'), ('food_nutrition', 'Food & Nutrition'), ('consultancy', 'Professional & Consultancy'), ('other', 'Other')], max_length=20),
        ),
    ]
