# Generated by Django 4.0.6 on 2022-09-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_advert_location_area_advert_location_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='9unytjsxkc1622wdfaub'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.itemcategory'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.itemtype'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='location_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.province'),
        ),
    ]
