# Generated by Django 4.0.6 on 2022-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_advert_advert_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='i417v3qco592z4wkwl40'),
        ),
    ]
