# Generated by Django 4.0.6 on 2022-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_advert_advert_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name_plural': 'Type'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Province'},
        ),
        migrations.AddField(
            model_name='advert',
            name='location_city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='advert',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='mne87vj9ds9byi0rtmax'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='cover_image',
            field=models.ImageField(default='placeholder_item_image.png', help_text='Recommended image size (300x300)px. Larger sizes will be reduced', upload_to='advert_cover_images'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='location_area',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
    ]
