# Generated by Django 4.0.6 on 2022-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_itemcategory_options_alter_itemtype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='x',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='advert',
            old_name='y',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='epx1bhec340lna2jxuue'),
        ),
    ]
