# Generated by Django 4.0.6 on 2022-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_rename_x_advert_lat_rename_y_advert_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_reference',
            field=models.TextField(default='fnaoptfsandn7qtp8nz2'),
        ),
    ]
